FROM node:24-bookworm

WORKDIR /app

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

RUN corepack enable && corepack prepare pnpm@10.29.3 --activate

CMD ["pnpm", "dev", "--hostname", "0.0.0.0"]
