export type RoastLevelSeed = {
  id: number
  name: string
}

export type TasteTagSeed = {
  id: number
  name: string
  tasteGroupId: number
}

export type CountrySeed = {
  id: number
  name: string
  area: string
}

export const roastLevelsSeedData: RoastLevelSeed[] = [
  { id: 0, name: "選択されていません" },
  { id: 1, name: "浅煎り" },
  { id: 2, name: "中浅煎り" },
  { id: 3, name: "中煎り" },
  { id: 4, name: "中深煎り" },
  { id: 5, name: "深煎り" },
]

export const tasteTagsSeedData: TasteTagSeed[] = [
  { id: 0, name: "選択されていません", tasteGroupId: 0 },
  { id: 1, name: "floral", tasteGroupId: 1 },
  { id: 2, name: "black tea", tasteGroupId: 1 },
  { id: 3, name: "chamomile", tasteGroupId: 1 },
  { id: 4, name: "rose", tasteGroupId: 1 },
  { id: 5, name: "jasmine", tasteGroupId: 1 },
  { id: 6, name: "berry", tasteGroupId: 6 },
  { id: 7, name: "blackberry", tasteGroupId: 6 },
  { id: 8, name: "raspberry", tasteGroupId: 6 },
  { id: 9, name: "blueberry", tasteGroupId: 6 },
  { id: 10, name: "strawberry", tasteGroupId: 6 },
  { id: 11, name: "dried fruit", tasteGroupId: 11 },
  { id: 12, name: "raisin", tasteGroupId: 11 },
  { id: 13, name: "prune", tasteGroupId: 11 },
  { id: 14, name: "fruit", tasteGroupId: 14 },
  { id: 15, name: "coconut", tasteGroupId: 14 },
  { id: 16, name: "cherry", tasteGroupId: 14 },
  { id: 17, name: "pineapple", tasteGroupId: 14 },
  { id: 18, name: "grape", tasteGroupId: 14 },
  { id: 19, name: "apple", tasteGroupId: 14 },
  { id: 20, name: "peach", tasteGroupId: 14 },
  { id: 21, name: "pear", tasteGroupId: 14 },
  { id: 22, name: "citrus", tasteGroupId: 22 },
  { id: 23, name: "grapefruit", tasteGroupId: 22 },
  { id: 24, name: "orange", tasteGroupId: 22 },
  { id: 25, name: "lemon", tasteGroupId: 22 },
  { id: 26, name: "lime", tasteGroupId: 22 },
  { id: 27, name: "fermented", tasteGroupId: 27 },
  { id: 28, name: "winey", tasteGroupId: 27 },
  { id: 29, name: "whiskey", tasteGroupId: 27 },
  { id: 30, name: "green", tasteGroupId: 30 },
  { id: 31, name: "olive oil", tasteGroupId: 30 },
  { id: 32, name: "peapod", tasteGroupId: 30 },
  { id: 33, name: "fresh", tasteGroupId: 30 },
  { id: 34, name: "dark green", tasteGroupId: 30 },
  { id: 35, name: "vegetable", tasteGroupId: 30 },
  { id: 36, name: "hay-like", tasteGroupId: 30 },
  { id: 37, name: "herb-like", tasteGroupId: 30 },
  { id: 38, name: "beany", tasteGroupId: 30 },
  { id: 39, name: "earthy", tasteGroupId: 39 },
  { id: 40, name: "woody", tasteGroupId: 39 },
  { id: 41, name: "roasted", tasteGroupId: 41 },
  { id: 42, name: "pipe tobacco", tasteGroupId: 41 },
  { id: 43, name: "tobacco", tasteGroupId: 41 },
  { id: 44, name: "burnt", tasteGroupId: 41 },
  { id: 45, name: "smoky", tasteGroupId: 41 },
  { id: 46, name: "cereal", tasteGroupId: 46 },
  { id: 47, name: "grain", tasteGroupId: 46 },
  { id: 48, name: "malt", tasteGroupId: 46 },
  { id: 49, name: "spice", tasteGroupId: 49 },
  { id: 50, name: "pungent", tasteGroupId: 49 },
  { id: 51, name: "pepper", tasteGroupId: 49 },
  { id: 52, name: "anise", tasteGroupId: 49 },
  { id: 53, name: "nutmeg", tasteGroupId: 49 },
  { id: 54, name: "cinnamon", tasteGroupId: 49 },
  { id: 55, name: "clove", tasteGroupId: 49 },
  { id: 56, name: "nutty", tasteGroupId: 56 },
  { id: 57, name: "peanuts", tasteGroupId: 56 },
  { id: 58, name: "hazelnut", tasteGroupId: 56 },
  { id: 59, name: "almond", tasteGroupId: 56 },
  { id: 60, name: "cocoa", tasteGroupId: 60 },
  { id: 61, name: "chocolate", tasteGroupId: 60 },
  { id: 62, name: "dark chocolate", tasteGroupId: 60 },
  { id: 63, name: "brown sugar", tasteGroupId: 63 },
  { id: 64, name: "molasses", tasteGroupId: 63 },
  { id: 65, name: "maple syrup", tasteGroupId: 63 },
  { id: 66, name: "caramel", tasteGroupId: 63 },
  { id: 67, name: "honey", tasteGroupId: 63 },
  { id: 68, name: "sweet", tasteGroupId: 68 },
  { id: 69, name: "vanilla", tasteGroupId: 68 },
  { id: 70, name: "sweet aromatics", tasteGroupId: 68 },
]

export const countriesSeedData: CountrySeed[] = [
  { id: 0, name: "選択されていません", area: "" },
  { id: 1, name: "ブラジル", area: "Latin America" },
  { id: 2, name: "ベトナム", area: "Asia" },
  { id: 3, name: "コロンビア", area: "Latin America" },
  { id: 4, name: "インドネシア", area: "Asia" },
  { id: 5, name: "エチオピア", area: "Africa" },
  { id: 6, name: "インド", area: "Asia" },
  { id: 7, name: "ホンジュラス", area: "Latin America" },
  { id: 8, name: "ペルー", area: "Latin America" },
  { id: 9, name: "ウガンダ", area: "Africa" },
  { id: 10, name: "メキシコ", area: "Latin America" },
  { id: 11, name: "グアテマラ", area: "Latin America" },
  { id: 12, name: "コートジボワール", area: "Africa" },
  { id: 13, name: "マレーシア", area: "Asia" },
  { id: 14, name: "コスタリカ", area: "Latin America" },
  { id: 15, name: "ニカラグア", area: "Latin America" },
  { id: 16, name: "タンザニア", area: "Africa" },
  { id: 17, name: "タイ", area: "Asia" },
  { id: 18, name: "パプアニューギニア", area: "Oceania" },
  { id: 19, name: "ケニア", area: "Africa" },
  { id: 20, name: "エルサルバドル", area: "Latin America" },
  { id: 21, name: "ベネズエラ", area: "Latin America" },
  { id: 22, name: "マダガスカル", area: "Africa" },
  { id: 23, name: "カメルーン", area: "Africa" },
  { id: 24, name: "フィリピン", area: "Asia" },
  { id: 25, name: "ラオス", area: "Asia" },
  { id: 26, name: "エクアドル", area: "Latin America" },
  { id: 27, name: "ドミニカ共和高", area: "Latin America" },
  { id: 28, name: "ハイチ", area: "Latin America" },
  { id: 29, name: "ルワンダ", area: "Africa" },
  { id: 30, name: "コンゴ民主共和国", area: "Africa" },
  { id: 31, name: "ブルンジ", area: "Africa" },
  { id: 32, name: "イエメン", area: "Asia" },
  { id: 33, name: "ボリビア", area: "Latin America" },
  { id: 34, name: "キューバ", area: "Latin America" },
  { id: 35, name: "パナマ", area: "Latin America" },
  { id: 36, name: "アメリカ(ハワイ)", area: "Oceania" },
  { id: 37, name: "ニカラグア", area: "Latin America" },
  { id: 38, name: "マラウェイ", area: "Africa" },
  { id: 39, name: "ジャマイカ", area: "Latin America" },
  { id: 40, name: "オーストラリア", area: "Oceania" },
  { id: 41, name: "中国", area: "Asia" },
  { id: 42, name: "東ティモール", area: "Asia" },
  { id: 43, name: "ネパール", area: "Asia" },
  { id: 44, name: "日本", area: "Asia" },
]
